name: AuraSteps
options:
  bundleIdPrefix: com.aurasteps
  deploymentTarget:
    iOS: 16.0
  developmentLanguage: es

targets:
  AuraSteps:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: .
    info:
      path: Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.aurasteps.app
      SWIFT_VERSION: "5.0"
      IPHONEOS_DEPLOYMENT_TARGET: "16.0"
      CODE_SIGNING_ALLOWED: "NO"
